### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Samir-OP** [valeriangalliat/spotify-to-youtube#2]
```
    return new WebapiRegularError(response.body, response.headers, response.statusCode);
           ^

WebapiRegularError: An error occurred while communicating with Spotify's Web API.
Details: No token provided.
```

**Comment by exiify** [comment]
May I see your code?

**Comment by Samir-OP** [comment]
```
const SpotifyToYoutube = require('spotify-to-youtube')
const SpotifyWebApi = require('spotify-web-api-node')

const spotifyApi = new SpotifyWebApi({
    clientId: "XXX",
    clientSecret: "XXX",
    redirectUri: "XXX"
})

// Do your auth thing here.



async function start() {
    
    const spotifyToYoutube = SpotifyToYoutube(spotifyApi)
    const id = await spotifyToYoutube('spotify:track:72jbDTw1piOOj770jWNeaG')
    console.log(id) 
}
start()
```

**Comment by exiify** [comment]
You need an access token

```
const SpotifyToYoutube = require("spotify-to-youtube");
const SpotifyWebApi = require("spotify-web-api-node");

const spotifyApi = new SpotifyWebApi({
  clientId: "xxx",
  clientSecret: "xxx",
});

// Do your auth thing here.

async function start() {
  await spotifyApi.clientCredentialsGrant().then(
    function (data) {
      console.log("The access token expires in " + data.body["expires_in"]);
      console.log("The access token is " + data.body["access_token"]);

    
      spotifyApi.setAccessToken(data.body["access_token"]);
    },
    function (err) {
      console.log(
        "Something went wrong when retrieving an access token",
        err.message
      );
    }
  );
  const spotifyToYoutube = SpotifyToYoutube(spotifyApi);
  const id = await spotifyToYoutube("spotify:track:72jbDTw1piOOj770jWNeaG");
  console.log(id);
}
start();
```

**Comment by Samir-OP** [comment]
I'm searching for the track
`spotify:track:5ygDXis42ncn6kYG14lEVG`
but it's giving me the different song 
https://www.youtube.com/watch?v=hH4u6CD81_Q

**Comment by exiify** [comment]
> I'm searching for the track
> `spotify:track:5ygDXis42ncn6kYG14lEVG`
> but it's giving me the different song
> https://www.youtube.com/watch?v=hH4u6CD81_Q

Yeah it's not perfect. A simple work around is if the spotify song's name is not in the youtube video title use another package to search for the spotify song name on youtube.

**Comment by Samir-OP** [comment]
```
C:\Users\hacke\Desktop\abcd\node_modules\spotify-web-api-node\src\http-manager.js:39
    return new WebapiRegularError(response.body, response.headers, response.statusCode);
           ^

WebapiRegularError: An error occurred while communicating with Spotify's Web API.
Details: too many ids requested.
    at _toError (C:\Users\hacke\Desktop\abcd\node_modules\spotify-web-api-node\src\http-manager.js:39:12)
    at C:\Users\hacke\Desktop\abcd\node_modules\spotify-web-api-node\src\http-manager.js:71:25
    at Request.callback (C:\Users\hacke\Desktop\abcd\node_modules\superagent\lib\node\index.js:905:3)
    at C:\Users\hacke\Desktop\abcd\node_modules\superagent\lib\node\index.js:1127:20
    at IncomingMessage.<anonymous> (C:\Users\hacke\Desktop\abcd\node_modules\superagent\lib\node\parsers\json.js:22:7)
    at Stream.emit (node:events:327:20)
    at Unzip.<anonymous> (C:\Users\hacke\Desktop\abcd\node_modules\superagent\lib\node\unzip.js:53:12)
    at Unzip.emit (node:events:327:20)
    at endReadableNT (node:internal/streams/readable:1289:12)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  body: { error: { status: 400, message: 'too many ids requested' } },
  headers: {
    'content-type': 'application/json; charset=utf-8',
    'cache-control': 'private, max-age=0',
    'x-robots-tag': 'noindex, nofollow',
    'access-control-allow-origin': '*',
    'access-control-allow-headers': 'Accept, App-Platform, Authorization, Content-Type, Origin, Retry-After, Spotify-App-Version, X-Cloud-Trace-Context, client-token, content-access-token',
    'access-control-allow-methods': 'GET, POST, OPTIONS, PUT, DELETE, PATCH',
    'access-control-allow-credentials': 'true',
    'access-control-max-age': '604800',
    'content-encoding': 'gzip',
    'strict-transport-security': 'max-age=31536000',
    'x-content-type-options': 'nosniff',
    date: 'Thu, 14 Jan 2021 15:54:41 GMT',
    server: 'envoy',
    via: 'HTTP/2 edgeproxy, 1.1 google',
    'alt-svc': 'clear',
    connection: 'close',
    'transfer-encoding': 'chunked'
  },
  statusCode: 400
}```

Playlist: https://open.spotify.com/playlist/4rnleEAOdmFAbRcNCgZMpY
